---
# tasks file for mongo.db

- name: create a repository
  file:
   path: /etc/yum.repos.d/mangodb.org.repo
   state: touch

- name: installation de gcc et python devel
  yum:
    name:
    - gcc
    - python-devel
    - python-setuptools
    state: present

- name: installation de pymongo
  easy_install:
    name: pymongo
    state: present

- name: connection remote via mongod.conf
  template:
    src: mongod.conf
    dest: /etc/mongod.conf

- name: complete file
  lineinfile:
   path: /etc/yum.repos.d/mangodb.org.repo
   line: "{{item}}"
  with_items:
   - "[mongodb-org-4.0]"
   - name=MongoDB Repository
   - baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.0/x86_64/
   - gpgcheck=1
   - enabled=1
   - gpgkey=https://www.mongodb.org/static/pgp/server-4.0.asc
 
- name: mise à jour package
  yum: 
   name: '*'
   state: latest
   update_cache: yes
  
- name: install the mongodb-org meta-package
  yum: 
   name: mongodb-org
   state: present 
  
- name: systemctl start mongod
  systemd:
   state: restarted
   name: mongod
   enabled: yes

- mongodb_user:
   database: admin
   name: root
   password: w32jjYdMZr
   roles: readWrite
   state: present

- name: create file service restfulweb
  file:
    path: /etc/systemd/system/restfulweb.service
    state: touch

- name: Config du fichier restfulweb.service
  blockinfile:
    path: /etc/systemd/system/restfulweb.service
    state: present
    block: |
      [Unit]
      Description=restfulweb Daemon
      After=network.target
      [Service]
      Environment=MONGO_DB=bddmygod
      Environment=MONGO_ADMIN=user
      Environment=MONGO_PWD=666
      Environment=MONGO_URL=10.0.3.17
      Environment=MONGO_PORT=27017
      Type=simple
      ExecStart=/opt/jdk-12.0.1/bin/java -jar /home/MounaSylvain/restfulweb-1.0.0-SNAPSHOT.jar
      [Install]
      WantedBy=multi-user.target
